name: template
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^7.6.4
  injectable: ^2.3.2
  equatable: ^2.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.8
  flutter_dotenv: ^5.1.0
  curved_navigation_bar: ^1.0.1
  shared_preferences: ^2.0.8
  dio: ^4.0.0
  flutter_spinkit: ^5.2.0
  intl: ^0.18.0
  flutter_cupertino_datetime_picker:
  flutter_slidable:
  drift: ^2.26.1
  drift_flutter: ^0.2.4
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  flutter_gen_runner: 5.10.0
  flutter_flavorizr: ^2.2.1
  injectable_generator: ^2.4.1
  drift_dev: ^2.26.1
  json_serializable: ^6.7.1
  logger: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    # - .env
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/svg_icons/

# region: flutter pub run build_runner build --delete-conflicting-outputs
flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true
    #flare_flutter: true
    rive: true
    lottie: true

# flavor region: flutter pub run flutter_flavorizr
flavorizr:
  flavors:
    prod:
      app:
        name: "$Trip"
      android:
        applicationId: "com.hieuld.demo"
      ios:
        bundleId: "com.hieuld.demo"
    dev:
      app:
        name: "$Trip Dev"
      android:
        applicationId: "dev.hieuld.demo"
      ios:
        bundleId: "dev.hieuld.demo"
